sudo: required
dist: trusty
language: go
go:
  - 1.5
go_import_path: github.com/zeroturnaround/configo
services: docker
install:
  - >
    if [[ $($HOME/bats/bin/bats --version) != "Bats 0.4.0" ]]; then
    mkdir -p $HOME/bats;
    curl -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar xvz --strip-components=1 -C $HOME/bats/;
    fi
  - make godep_restore
script:
  - make test
  - make itest