sudo: required
dist: trusty
language: go
go:
  - 1.5
go_import_path: github.com/zeroturnaround/configo
services: docker
install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - make godep_restore
script:
  - make test
  - make itest